using System;
using System.Diagnostics;
using System.Web.Configuration;

namespace AssetManagement.Web.Security
{
    /// <summary>
    /// Warns when Release builds rely on auto-generated machine keys instead of an explicit
    /// machineKey.config (required for web farms and recommended for production).
    /// </summary>
    public static class MachineKeyDeploymentValidator
    {
        private const string PlaceholderToken = "REPLACE_WITH_";

        public static void WarnIfMissingInProduction()
        {
            if (IsDebugCompilation())
            {
                return;
            }

            var section = WebConfigurationManager.GetSection("system.web/machineKey") as MachineKeySection;
            if (section == null)
            {
                Trace.TraceWarning(
                    "AssetManagement: machineKey is not configured. Forms Authentication cookies may fail across app pool recycles or web-farm nodes. Copy machineKey.config.example to machineKey.config and set unique keys before production deployment.");
                return;
            }

            if (UsesAutoGeneratedKey(section.ValidationKey) || UsesAutoGeneratedKey(section.DecryptionKey))
            {
                Trace.TraceWarning(
                    "AssetManagement: machineKey uses auto-generated keys. For production and web farms, copy machineKey.config.example to machineKey.config, generate unique validation/decryption keys, and deploy the same file to every IIS node.");
                return;
            }

            if (ContainsPlaceholder(section.ValidationKey) || ContainsPlaceholder(section.DecryptionKey))
            {
                Trace.TraceWarning(
                    "AssetManagement: machineKey.config still contains placeholder values. Replace REPLACE_WITH_* tokens with cryptographically random hex keys before go-live.");
            }
        }

        private static bool IsDebugCompilation()
        {
            var compilation = WebConfigurationManager.GetSection("system.web/compilation") as CompilationSection;
            return compilation != null && compilation.Debug;
        }

        private static bool UsesAutoGeneratedKey(string key)
        {
            return string.IsNullOrWhiteSpace(key)
                || key.IndexOf("AutoGenerate", StringComparison.OrdinalIgnoreCase) >= 0;
        }

        private static bool ContainsPlaceholder(string key)
        {
            return !string.IsNullOrWhiteSpace(key)
                && key.IndexOf(PlaceholderToken, StringComparison.OrdinalIgnoreCase) >= 0;
        }
    }
}
